package org.example.states;

public enum BotState{
    START,
    REGISTER_TEACHER,
    REGISTER_STUDENT,
    MENU_ADMIN,
    MENU_STUDENT,
    CHOOSE_TYPE,
    UPDATE_SUBJECT,
    UPDATE_NAME,
    CONFIRM,
    MAIN_MENU,
    SEND_HOMEWORK,
    SEND_CWORK,
    SEND_REQ_WEEKLY,
    SEND_REQ_MONTHLY,
    TEACHER_PAGE,
    REG_TEACH_CLASS
}
